- .babelrc
- .editorconfig
- .gitignore
- .nycrc
- .travis.yml
- README.md
- codecov.yml
- package.json
We got ourselves a nice, automated code coverage tool now!
Finally, is it ready to be reviewed and merged: YES :white_check_mark:
1. Pick one of the commits (that work) from [here](https://codecov.io/gh/TheFourFifths/consus/commits)
1. Witness the beauty of our code coverage report
- [TFF-67](https://msoese.atlassian.net/browse/TFF-67)
- [Codecov.io consus](https://codecov.io/gh/TheFourFifths/consus)
> Add Code Coverage

- src/api/student.js
- src/store/checkin-store.js
- src/store/checkout-store.js
- src/store/item-store.js
- src/store/model-store.js
- src/store/student-store.js
- test/unit/store/checkin-store.js
- test/unit/store/checkout-store.js
- test/unit/store/item-store.js
- test/unit/store/model-store.js
- test/unit/store/student-store.js
- test/util/database.js
This PR updates the stores on the server to handle item check-in requests.
Finally, is it ready to be reviewed and merged: yes :cactus: 
1. Verify that checked-in items are removed from the student's item list.
2. Verify that checked-in items are available for check-out.
- [TFF-74](https://msoese.atlassian.net/browse/TFF-74)
> Server-side store

- .gitignore
- docs/REST.md
- src/api/model.js
- src/store/model-store.js
Add data related to models(manufactor, price, desc)
Finally, is it ready to be reviewed and merged: yes :white_check_mark:
1. Run `npm test`?
Put links to Jira tickets, and anything else, here.
- [TFF-91](https://msoese.atlassian.net/browse/TFF-91)
> Add model data tff91

- src/api/student.js
Adds a check to the API endpoint for a missing student. If the student could not be found, it returns the error "The student could not be found."
Finally, is it ready to be reviewed and merged: yes :white_check_mark:
1. Verify that the `GET /api/student` endpoint returns an appropriate error message for an invalid/missing student id.
- [TFF-77](https://msoese.atlassian.net/browse/TFF-77)
- [Sister PR to consus-client](https://github.com/TheFourFifths/consus-client/pull/18)
> TFF 77: Invalid student id

- docs/REST.md
- src/api/item.js
- src/store/item-store.js
- test/unit/store/item-store.js
You can delete an item by sending at DELETE request with the param itemAddress = <address>. 
Finally, is it ready to be reviewed and merged: yes
1. Look at code changes
2. Be amazed
Put links to Jira tickets, and anything else, here.
- [TFF-112](https://msoese.atlassian.net/browse/TFF-112)
> Delete item tff122

- docs/REST.md
- src/api/item.js
- src/store/item-store.js
- test/unit/store/item-store.js
Delete an item
Finally, is it ready to be reviewed and merged: yes :white_check_mark: / no :red_circle:
1. Send a delete request to the server with the itemAddress to delete.
Put links to Jira tickets, and anything else, here.
- [TFF-37](https://msoese.atlassian.net/browse/TFF-37)
> Item destruction story

- docs/Actions.md
I added a file called `docs/Actions.md` that describes the actions used in this repo.
1. Read my words, and verify the words are correct.
- [TFF-155](https://msoese.atlassian.net/browse/TFF-155)
> Document actions [TFF-155]

- docs/Actions.md
- docs/REST.md
- package.json
- src/api/student.js
- src/store/student-store.js
- test/unit/store/student-store.js
This story allows tech support to upload an Excel file to add/update students.
- [TFF-102](https://msoese.atlassian.net/browse/TFF-102)
> Student import [TFF-102]

- test/functional/get-all-items.js
Functional test for getAllItems method. Tests using the API
1. Check out this branch.
1. npm install if you haven't gotten the functional test stuff yet.
1. Run npm test
1. Verify that the getAllItem tests is running and passing.
1. Review test for throughness and clarity.
- [TFF-143](https://msoese.atlassian.net/browse/TFF-143)
> Functional test for getAllItems

- src/api/item.js
- test/functional/new-item.js
Another functional test for the server. It uses the API to test adding a new item.
1. Check out this branch.
2. npm install if you haven't gotten the functional test stuff yet.
3. Run npm test
4. Verify that the new item tests are running and passing.
5. Review tests for throughness and clarity.
- [TFF-139](https://msoese.atlassian.net/browse/TFF-139)
> New item test tff 139

- docs/REST.md
Somebody forgot to switch the `modelId` to `modelAddress`
1. Read
1. Make sure I'm not lying
_None._
> Somebody forgot to switch the `modelId` to `modelAddress`

- docs/REST.md
- src/api/item.js
- src/store/item-store.js
- test/unit/store/item-store.js
Gets us closer to letting the user see overdue items.
1. Read docs
1. `npm t`
- [TFF-43](https://msoese.atlassian.net/browse/TFF-43)
- TheFourFifths/consus-client#84
> Overdue items page [TFF-43]

- src/api/checkout.js
- test/functional/checkout.js
Functional tests for the checkout API.
1. Check the tests.
2. Test the tests.
- [TFF-134](https://msoese.atlassian.net/browse/TFF-134)
> Functional test: Check out items

- src/data/items.js
- src/data/models.js
- src/data/students.js
- src/index.js
- src/lib/data-setup.js
- src/store/item-store.js
- src/store/model-store.js
- src/store/student-store.js
- test/unit/lib/data-setup.js
New method of generating default data to stores rather than just initializing stores with data in the arrays.  the ```/lib/data-setup``` file contains an ```initData()``` function called by index.js that calls actions to set default server state.  ```/data``` directory holds arrays with the data necessary to generate new students, models, and items.
1. Run with client on dev
2. Build and start the server, make sure there are no errors.
3. All the defaults should be the same as before and functioning properly.  Boaty should have an overdue item, and checking it in should work.
- [TFF-192](https://msoese.atlassian.net/browse/TFF-192)
> Changed method of generating store data to replace the really bad hotfix

- docs/REST.md
- src/api/student.js
- src/store/student-store.js
- test/functional/get-all-students.js
- test/functional/update-student.js
An endpoint to update a student via the API.
1. Make sure the tests make sense and the code looks good.
- [TFF-194](https://msoese.atlassian.net/browse/TFF-194)
> Update Student API endpoint for TFF-194

- .gitignore
- docs/Actions.md
- src/api/checkout.js
- src/store/checkout-store.js
- src/store/item-store.js
- src/store/model-store.js
- src/store/student-store.js
- test/functional/checkout-longterm.js
Just one task. Getting this into dev so that I can refactor the model data.
1. Don't. It's no different than the task->story PR was was already reviewed.
- [TFF-153](https://msoese.atlassian.net/browse/TFF-153)
> [TFF-153] Longterm Checkout

- .editorconfig
- .gitignore
- bin/consusd
- config/custom-environment-variables.toml
- config/default.toml
- package.json
- src/index.js
- src/lib/email.js
- src/lib/server.js
- src/store/item-store.js
- src/store/model-store.js
- src/store/student-store.js
You can now configure things at runtime using files in `config/`. We can also have a bunch of different configs for different deployment destinations, hosts, and instances (see https://github.com/lorenwest/node-config/wiki/Configuration-Files). See [Confluence](https://msoese.atlassian.net/wiki/x/dybRBQ) when you get an error about nodemailer and Gmail.
Run with same branch on both ends.
1. Think of every place a config value could be useful
1. Read the codes/configs
1. Think of every place a config value could be useful, that isn't included
- [TFF-173](https://msoese.atlassian.net/browse/TFF-173)
- TheFourFifths/consus-client/pull/109
> [TFF-173] Config file

- src/store/student-store.js
- test/functional/get-all-students.js
- test/functional/update-student.js
- test/unit/store/student-store.js
Added RFID to student objects, fixed functional tests. Added access functions and unit tests.
1. Make sure code looks good and run tests.
- [TFF-208](https://msoese.atlassian.net/browse/TFF-208)
> Added RFID to students with functions and tests [tff-208]

- test/functional/edit-item-duedate.js
Travis has timezone issues with our tests. This should fix it.
1. Verify travis runs correctly
> Fix travis timezone issues on edit dates

- src/data/models.js
> Model renamed

- docs/Actions.md
- docs/REST.md
- src/api/student.js
- src/data/students.js
- src/store/student-store.js
- test/functional/add-rfid-to-student.js
- test/functional/get-all-students.js
- test/functional/update-student.js
- test/unit/lib/data-setup.js
- test/unit/store/student-store.js
Change the UPDATE_STUDENT action to take rfids and add endpoint for adding an rfid to a student.
1. Review code
2. Verify this works with client pr
- [TFF-207](https://msoese.atlassian.net/browse/TFF-207)
- TheFourFifths/consus-client/pull/126
> StudentID to rfid association 

- docs/Actions.md
- docs/REST.md
- src/api/item.js
- src/api/model.js
- src/lib/clock.js
- src/store/item-store.js
- src/store/student-store.js
- test/functional/retrieve-item.js
- test/functional/retrieve-model.js
- test/functional/save-item.js
- test/functional/save-model.js
- test/unit/store/item-store.js
- test/unit/store/student-store.js
We can now save and retrieve equipment.
1. Run both the server and client on `item-saving-TFF-39-story`.
2. Create a model that can be checked out.
3. Check out a model and an item.
4. Save them both.
5. Retrieve them both (by scanning the address into the cart input and/or by clicking "Retrieve").
- [TFF-39](https://msoese.atlassian.net/browse/TFF-39)
- TheFourFifths/consus-client/pull/131
> [TFF-39] Item Saving and Retrieving

- src/api/student.js
- test/functional/create-new-student.js
- test/unit/lib/email.js
- test/unit/store/student-store.js
Change some of the end points to accommodate for new student. Add endpoint for creating a student.
Also removing pesky assert in edit duedate. 
1. Review code
2. Look a client
- [TFF-209](https://msoese.atlassian.net/browse/TFF-209)
- TheFourFifths/consus-client/pull/tbd
> Student not found tff209

- docs/REST.md
- src/api/model.js
- src/store/model-store.js
- test/functional/new-model.js
Ability to upload a photo when creating models.
DO NOT MERGE ME UNTIL END OF SPRINT!!!!
1. Check the code.
2.  Testing only works with the UI branches, so use this when testing those
> Added photo upload to model creation

- test/unit/store/checkout-store.js
We actually fixed this already during the model refactor: https://github.com/TheFourFifths/consus/commit/d883f81fe118ecf9bc3b3b00d240ec2618907a21#diff-797110edd2bd947b1744555a4a4b80c0R46
This PR just adds a test to verify that it works.
1. Review the test. There's only one.
- [TFF-184](https://msoese.atlassian.net/browse/TFF-184)
> [TFF-184] Validate quantity of model being checked out

- src/data/students.js
- src/store/student-store.js
- test/functional/get-all-students.js
- test/functional/update-student.js
Adding slot to students to keep track of items they turned in late.
1. Go the the client side PR, test it
2.Make sure code makes sense
- [TFF-29](https://msoese.atlassian.net/browse/TFF-238)
- TheFourFifths/consus-client/pull/135
> Deliquents tff238

- .gitignore
- Gruntfile.js
- README.md
- config/default.toml
- package.json
- src/data-setup.js
- src/data/checkouts.js
- src/index.js
- src/lib/data-setup.js
- src/lib/database.js
- src/lib/server.js
- test/unit/lib/data-setup.js
I found [this cool Node.js database](https://www.npmjs.com/package/oak-lite) and configured Consus to use it for persistent action storage.
1. `npm install`
2. `npm run data-setup` (This will do the usual data setup, but actually put the actions into persistent storage.)
3. `npm start`
4. Run the client
5. Verify that the sample data is appearing in the client
6. Add a new item
7. Close the client, shut down the server
8. Restart the server
9. Run the client again
10. Verify that everything is still there (the sample data + the new item)
- [TFF-239](https://msoese.atlassian.net/browse/TFF-239)
> [TFF-239] Persistent database
